version: '3'
services:
  service-db:
    image: "mysql:8"
    container_name: service-db
    ports:
      - 13306:3306
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_DATABASE=crypto-db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password